import "../styles/globals.scss";
import { Provider } from "react-redux";
import React from "react";
import store from "../store";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Header } from "./components/header.component";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </Provider>
  );
}
export default MyApp;
